# Generated by Django 5.1.7 on 2025-04-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.AddField(
            model_name='apartment',
            name='reservation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('kvitansiya', 'Kvitansiya'), ('shartnoma', 'Shartnoma'), ('chek', 'Chek'), ('boshqa', 'Boshqa')], default='shartnoma', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/images/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('bosh', 'Bo‘sh'), ('band', 'Band qilingan'), ('muddatli', 'Muddatli'), ('sotilgan', 'Sotilgan'), ('ipoteka', 'Ipoteka'), ('subsidiya', 'Subsidiya')], default='bosh', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('muddatli', 'Muddatli to‘lov'), ('ipoteka', 'Ipoteka'), ('subsidiya', 'Subsidiya'), ('band', 'Band qilish')], default='naqd', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('naqd', 'Naqd pul'), ('muddatli', 'Muddatli to‘lov'), ('ipoteka', 'Ipoteka')], default='naqd', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='all.supplier')),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi to‘lovi',
                'verbose_name_plural': 'Yetkazib beruvchi to‘lovlari',
            },
        ),
    ]
